### PR TITLE
Link to TC39 spec

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Comment by littledan** [comment]
Huh? I thought we were going to keep linking to the previous spec until we met certain exit criteria #35 . We can link to the under-development spec, but we shouldn't identify it as v3 at this point.

**Comment by jridgewell** [comment]
Before we publish our own specification, sure it'd make sense to hit those exit criteria. But I think it's completely reasonable for our RFC repo to directly link to our spec repo.

**Comment by nicolo-ribaudo** [comment]
Isn't this like linking to tc39.es/ecma262 rather than to a published version? i.e. the draft source maps spec is already an improvement over the Google doc, but it's still not published and marked as draft (until we meet the exit criteria)

**Comment by littledan** [comment]
Yeah, I wanted us to get to those exit criteria before publishing something equivalent to tc39.es/ecma262 (which is viewed as an authoritative reference, as it should be, even though it doesn't have official status) and then we can continue updating this draft as a "living standard".

What I would prefer is if we did link to this draft, but identified it as "not 100% ready yet", and also linked to the previous v3 spec, and identified it as "historical"--this patch just identifies the current draft as v3, which seems confusing.

Anyway, maybe we should consider ourselves to have met whatever minimum exit-to-promoted-draft milestone; I would have just preferred explicit discussion/acknowledgement of this.

**Comment by nicolo-ribaudo** [comment]
> What I would prefer is if we did link to this draft, but identified it as "not 100% ready yet", and also linked to the previous v3 spec, and identified it as "historical"

In the first few lines of the draft document it says that it's a strawman and it links to the historical version -- do you suggest to also keep both links in the readme?

> Anyway, maybe we should consider ourselves to have met whatever minimum exit-to-promoted-draft milestone; I would have just preferred explicit discussion/acknowledgement of this.

Yes I agree we should discuss together whether we meet some minimum requirement yet, but I disagree that linking to the draft we're working on in this repo is marking it as "ready" in any way.

Anyway, let's revert this and discuss it at the next meeting?

**Pull request merged**
